# Generated by Django 5.2.10 on 2026-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('keyword', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
